### ISSUE TITLE
Loading a save makes objects invisible

### ISSUE THREAD

**Issue by bosshunter** [Rinnegatamante/vitaWolfen#4]
Most of the time, loading a save file makes objects invisible (enemies, corpses, drops and decoration objects) at certain angles of vision.

Sometimes loading a save, throws the C2-12828-1 psp2core error.

Edit: Same behavior in both Shareware and Full versions of Wolfenstein and Spear of Destiny.

![recentral 2017-06-01 22-27-39-54](https://cloud.githubusercontent.com/assets/3970315/26701567/89fe416a-4719-11e7-9a3c-b0ba34a0d247.png)
![recentral 2017-06-01 22-27-29-85](https://cloud.githubusercontent.com/assets/3970315/26701569/8af964d2-4719-11e7-800c-777d966349d2.png)

**Comment by Rinnegatamante** [comment]
Can you try to replace your eboot0.bin file in app0:/ vitaWolfen folder with this and try to perform the crash with the Shareware version? If you get it, upload somewhere the psp2dmp.

[eboot0.zip](https://github.com/Rinnegatamante/vitaWolfen/files/1057588/eboot0.zip)

**Comment by bosshunter** [comment]
It was hard to recreate the crash, but eventually happened.

<a href="http://www.mediafire.com/file/9ktbxvm82url6dv/psp2core-1496878544-0x00001b227f-eboot0.bin.psp2dmp">psp2core-1496878544-0x00001b227f-eboot0.bin.psp2dmp</a>

**Comment by Rinnegatamante** [comment]
Seems like the elf produced was invalid :/ Need one more crashdump with this: http://rinnegatamante.it/eboot0.zip

**Comment by bosshunter** [comment]
Had several crashed on shareware boot: <a href="http://www.mediafire.com/file/fdz3sxlvs8t943x/psp2core.zip">psp2core.zip</a>

The psp2core-1497055716-0x0000e52b37-eboot0.bin was when the guards shot me dead.

**Comment by Rinnegatamante** [comment]
So, in what circumstances these crashes happened?

**Comment by bosshunter** [comment]
3 of them (the smaller ones) was when I pressed X to load the shareware version. And the bigger one was when the guards shot me dead. I tried to recreate again a crash when loading a save, but it didn't happen.
