### ISSUE TITLE
Vitawolfen crashes when the player dies

### ISSUE THREAD

**Issue by Count-Duckula-AU** [Rinnegatamante/vitaWolfen#7]
This issue has been discussed here: https://wololo.net/talk/viewtopic.php?f=116&t=46288&start=40#p423179

The game crashes when dying with the debug version from the wololo link above.

Vita is on 3.60 with enso
Wolfenstein (full version) datafiles are from GOG
Core: Wolfenstein 3d Full

-Uninstalled the vitawolfen 1.5 bubble, installed the debug version
-Deleted all contents of ux0:data/vitawolfen, copied just the wl6 files from the GOG release of wolf 3d into that location
-Started new game, all default settings 
-Let the first enemy kill me, game crashes

Video: https://youtu.be/FOCo4K29diM

Coredump attached.

[psp2core-1532925885-0x00002e2587-eboot10.bin.zip](https://github.com/Rinnegatamante/vitaWolfen/files/2239718/psp2core-1532925885-0x00002e2587-eboot10.bin.zip)

Thanks Rinnegatamante. If it helps with troubleshooting I'd be happy to send you a gift link for the GOG version of wolf3d/SOD.

**Comment by Rinnegatamante** [comment]
Both Spear of Destiny Demo and Shareware cores seems not to crash. That's quite a strange issue. Going to take a look at the coredump.

**Comment by Rinnegatamante** [comment]
Looks like it's an issue related to a free usage on an already freed memory location. Do you have Discord so i can ask you for some further tests?

**Comment by olokos** [comment]
I don't know why is this closed as the bug is still valid. Shareware doesnt crash, but full game does and there's no solution given here.
