### ISSUE TITLE
Missing compile instructions

### ISSUE THREAD

**Issue by 01y** [Rinnegatamante/vitaWolfen#8]
This appears to require custom versions of libraries in VitaSDK, but it doesn't specify which ones. Have tried using versions of each on your github repositories (SDL-Vita, imgui, vitaGL, etc.), managed to successfully compile, but the result does not correctly display video when run. Possible to use submodules to incorporate these for easier setup?

**Comment by olokos** [comment]
I think I found the problem, at least with vitaGL
We need to use vitaGL code from this commit https://github.com/Rinnegatamante/vitaGL/commit/f0f9f150b1e4e00300f2baf2ec53086a99482454 as this commit https://github.com/Rinnegatamante/vitaGL/commit/cc7340eb1428aca5cd535ecab0bc8dbd3bb7d9cd
removes vglMapHeapMem which is explicitely used by vitaWolfen
I will make a pull request with more fixes that had to be made to build it properly once I got it solved

**Comment by Rinnegatamante** [comment]
You need those that are not on vdpm:
- https://github.com/Rinnegatamante/vitaGL
- https://github.com/Rinnegatamante/SDL-Vita/tree/sdl12_gl
- https://github.com/Rinnegatamante/imgui-vita

If you feel like adding them as submodules, don't hesitate to drop a PR, i'll merge it.
